version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-topics:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    volumes:
      - ./kafka-topics.sh:/kafka-topics.sh
    command: ["sh", "/kafka-topics.sh"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server"]

  supernode:
    build: ./supernode
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - redis
    command: ["python", "app.py"]

  supernode-replica:
    build: ./supernode-replica
    depends_on:
      - kafka
      - redis
    command: ["python", "app.py"]

  cluster1-node1:
    build: ./cluster
    depends_on:
      - kafka
      - supernode
    command: ["python", "node.py", "1", "1"]
    ports:
      - "5001:5001"
    volumes:
      - ./cluster_logs:/app/logs
      - ./node_files/node1:/app/node_files

  cluster1-node2:
    build: ./cluster
    depends_on:
      - kafka
      - supernode
    command: ["python", "node.py", "2", "1"]
    ports:
      - "5002:5002"
    volumes:
      - ./cluster_logs:/app/logs
      - ./node_files/node2:/app/node_files

  cluster1-node3:
    build: ./cluster
    depends_on:
      - kafka
      - supernode
    command: ["python", "node.py", "3", "1"]
    ports:
      - "5003:5003"
    volumes:
      - ./cluster_logs:/app/logs
      - ./node_files/node3:/app/node_files

  cluster2-node4:
    build: ./cluster
    depends_on:
      - kafka
      - supernode
    command: ["python", "node.py", "4", "2"]
    ports:
      - "5004:5004"
    volumes:
      - ./cluster_logs:/app/logs
      - ./node_files/node4:/app/node_files

  cluster2-node5:
    build: ./cluster
    depends_on:
      - kafka
      - supernode
    command: ["python", "node.py", "5", "2"]
    ports:
      - "5005:5005"
    volumes:
      - ./cluster_logs:/app/logs
      - ./node_files/node5:/app/node_files

  cluster2-node6:
    build: ./cluster
    depends_on:
      - kafka
      - supernode
    command: ["python", "node.py", "6", "2"]
    ports:
      - "5006:5006"
    volumes:
      - ./cluster_logs:/app/logs
      - ./node_files/node6:/app/node_files

  watchdog-cluster1:  # Watchdog for Cluster 1
    build: ./cluster
    depends_on:
      - kafka
    command: ["python", "watchdog.py", "1"]
    volumes:
      - ./cluster_logs:/app/logs

  watchdog-cluster2:  # Watchdog for Cluster 2
    build: ./cluster
    depends_on:
      - kafka
    command: ["python", "watchdog.py", "2"]
    volumes:
      - ./cluster_logs:/app/logs

  kafka-monitor:
    build: ./cluster
    depends_on:
      - kafka
    command: ["python", "kafka_monitor.py", "--from-beginning"]
    volumes:
      - ./cluster_logs:/app/logs

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - supernode
    command: ["sh", "-c", "npm start"]

volumes:
  cluster_logs:
  node_files: